[platformio]
default_envs = grid_es3c28p
boards_dir = boards
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = hosyond_es3c28p
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
lib_deps = bodmer/TFT_eSPI@2.5.43
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DUSE_HSPI_PORT=1
    -include $PROJECT_DIR/include/es3c28p_tft_setup.h

[env:grid_es3c28p]
build_src_filter = +<main.cpp> +<touch_ft6336.cpp>
extra_scripts = post:scripts/merge_factory.py

[env:grid_return_test]
build_src_filter = +<return_test.cpp> +<touch_ft6336.cpp>
extra_scripts = post:scripts/copy_test_payload.py
